-- CREATE USER STATEMENTS
CREATE USER ADMIN;
CREATE USER DEVELOPER;
CREATE USER TESTER;
CREATE USER END_USER;

-- DROP USERS STATEMENTS
DROP USER ADMIN;
DROP USER DEVELOPER;
DROP USER TESTER;
DROP USER END_USER;

-- GRANT STATEMENTS
GRANT ALL ON hospital_mgmt_sys.* TO ADMIN;
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON hospital_mgmt_sys.* TO DEVELOPER;
GRANT SELECT, INSERT, UPDATE, DELETE ON hospital_mgmt_sys.* TO TESTER;
GRANT SELECT ON hospital_mgmt_sys.* TO END_USER;

-- REVOKE STATEMENTS
REVOKE ALL ON hospital_mgmt_sys.* FROM ADMIN;
REVOKE SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES ON hospital_mgmt_sys.* FROM DEVELOPER;
REVOKE SELECT, INSERT, UPDATE, DELETE ON hospital_mgmt_sys.* FROM TESTER;
REVOKE SELECT ON hospital_mgmt_sys.* FROM END_USER;