/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import Business.Enterprise.Enterprise;
import Business.UserAccount.UserAccount;
import UserInterface.AdministrativeRole.ManageOrganizationJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Leandra
 */
public class CustomerLoginJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise e;
    UserAccount ua;

    /**
     * Creates new form CustomerLoginJPanel
     */
    public CustomerLoginJPanel(JPanel userProcessContainer, Enterprise e, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.e = e;
        this.ua = ua;
        customerNamejLabel.setText(ua.getEmployee().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        destinationjTextField = new javax.swing.JTextField();
        gojButton = new javax.swing.JButton();
        welcomejLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sourcejTextField1 = new javax.swing.JTextField();
        customerNamejLabel = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        jLabel7.setText("jLabel7");

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Please Enter your destination");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Hey ");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, -1, 22));

        destinationjTextField.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        add(destinationjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 118, -1));

        gojButton.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        gojButton.setText("Go");
        gojButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gojButtonActionPerformed(evt);
            }
        });
        add(gojButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 81, 47));
        add(welcomejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(749, 101, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("use our application to find the status of the road as per your destination");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 548, -1));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Please Enter your source");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, -1, -1));

        sourcejTextField1.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        sourcejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sourcejTextField1ActionPerformed(evt);
            }
        });
        add(sourcejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 118, -1));

        customerNamejLabel.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        customerNamejLabel.setForeground(new java.awt.Color(255, 255, 255));
        add(customerNamejLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 100, 26));

        jLabel6.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Welcome to Smart Way ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 790, 69));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leandra\\Documents\\GitHub\\menezes_leandra_001621189\\menezes_leandra_001621189\\Project\\SmartRoadSensors\\images\\Smart-Highway-Glowing-Lines-Daan-Roosegaarde-3.jpg")); // NOI18N
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 700));

        jLabel9.setText("jLabel9");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 660, 90));
    }// </editor-fold>//GEN-END:initComponents

    private void sourcejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sourcejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sourcejTextField1ActionPerformed

    private void gojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gojButtonActionPerformed
        // TODO add your handling code here:
        if (sourcejTextField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the source");
        } else if (destinationjTextField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please Enter the destination");
        } else {
            String source = sourcejTextField1.getText();
            String destination = destinationjTextField.getText();
            CustomerRoadDetailsJPanel customerRoadDetailsJPanel = new CustomerRoadDetailsJPanel(userProcessContainer, e, ua, source, destination);
            userProcessContainer.add("customerRoadDetailsJPanel", customerRoadDetailsJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
            sourcejTextField1.setText("");
            destinationjTextField.setText("");
        }
    }//GEN-LAST:event_gojButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel customerNamejLabel;
    private javax.swing.JTextField destinationjTextField;
    private javax.swing.JButton gojButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField sourcejTextField1;
    private javax.swing.JLabel welcomejLabel;
    // End of variables declaration//GEN-END:variables

}
