/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RoadMaintainenceRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Leandra
 */
public class RoadMaintenanceAuthorityWorkAreaJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise e;
    Organization o;
    UserAccount ua;

    /**
     * Creates new form RoadMaintenanceAuthorityWorkAreaJPanel
     */
    public RoadMaintenanceAuthorityWorkAreaJPanel(JPanel userProcessContainer, Enterprise e, Organization o, UserAccount ua) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.e = e;
        this.o = o;
        this.ua = ua;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createRoadjButton = new javax.swing.JButton();
        maintainRoadjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(null);

        createRoadjButton.setBackground(new java.awt.Color(204, 204, 204));
        createRoadjButton.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        createRoadjButton.setText("Create Road");
        createRoadjButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createRoadjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRoadjButtonActionPerformed(evt);
            }
        });
        add(createRoadjButton);
        createRoadjButton.setBounds(50, 140, 160, 110);

        maintainRoadjButton.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        maintainRoadjButton.setText("Maintain Road");
        maintainRoadjButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        maintainRoadjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maintainRoadjButtonActionPerformed(evt);
            }
        });
        add(maintainRoadjButton);
        maintainRoadjButton.setBounds(50, 340, 160, 130);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setText("Road Maintainence Authority Work Area");
        add(jLabel1);
        jLabel1.setBounds(30, 10, 744, 65);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Leandra\\Documents\\GitHub\\menezes_leandra_001621189\\menezes_leandra_001621189\\Project\\SmartRoadSensors\\images\\600px-Under_construction_icon-blue-300x250.png")); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(390, 150, 360, 270);
    }// </editor-fold>//GEN-END:initComponents

    private void createRoadjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRoadjButtonActionPerformed
        // TODO add your handling code here:
        CreateRoadJPanel createRoadJPanel = new CreateRoadJPanel(userProcessContainer, o, e, ua);
        userProcessContainer.add("createRoadJPanel", createRoadJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_createRoadjButtonActionPerformed

    private void maintainRoadjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maintainRoadjButtonActionPerformed
        // TODO add your handling code here:
        MaintainRoadJPanel maintainRoadJPanel = new MaintainRoadJPanel(userProcessContainer, o, ua, e);
        userProcessContainer.add("maintainRoadJPanel", maintainRoadJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_maintainRoadjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createRoadjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton maintainRoadjButton;
    // End of variables declaration//GEN-END:variables
}
