/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TrafficControlProcessorRole;

import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.RoadMaintenanceOrganization;
import Business.Road.Road;
import Business.Sensor.Sensor;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MaintainenceWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Leandra
 */
public class CreateRoadRequestJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    Enterprise e;
    Road r;
    UserAccount ua;
    String sensorLocationId;

    /**
     * Creates new form CreateRoadRequestJPanel
     */
    public CreateRoadRequestJPanel(JPanel userProcessContainer, Enterprise e, Road r, UserAccount ua, String sensorLocationId) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.e = e;
        this.r = r;
        this.ua = ua;
        this.sensorLocationId = sensorLocationId;
        roadIdjTextField.setText(String.valueOf(r.getRoadid()));
        roadNamejTextField.setText(r.getRoadName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        roadIdjTextField = new javax.swing.JTextField();
        roadNamejTextField = new javax.swing.JTextField();
        problemjTextField = new javax.swing.JTextField();
        backjButton = new javax.swing.JButton();
        createRoadRequestjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        problemjLabel = new javax.swing.JLabel();

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel3.setText("Road Name");

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel5.setText("Problem");

        roadIdjTextField.setEditable(false);
        roadIdjTextField.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N

        roadNamejTextField.setEditable(false);
        roadNamejTextField.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N

        problemjTextField.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        problemjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                problemjTextFieldActionPerformed(evt);
            }
        });

        backjButton.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        backjButton.setText("Back");
        backjButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        createRoadRequestjButton.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        createRoadRequestjButton.setText("Create Road Request");
        createRoadRequestjButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        createRoadRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createRoadRequestjButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setText("Road Request ");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel2.setText("Road ID");

        problemjLabel.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(backjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(createRoadRequestjButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(290, 290, 290)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(problemjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roadNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(roadIdjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(78, 78, 78)
                        .addComponent(problemjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(roadIdjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roadNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(problemjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(problemjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createRoadRequestjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(153, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        TrafficControlProcessorWorkAreaJPanel tcpwjp = (TrafficControlProcessorWorkAreaJPanel) component;
        tcpwjp.populateRequestTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed

    private void createRoadRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createRoadRequestjButtonActionPerformed
        // TODO add your handling code here:

        try {

            boolean problemTrue = validateProblem();

            if (problemTrue) {

                String message = problemjTextField.getText();
                MaintainenceWorkRequest request = new MaintainenceWorkRequest();
                for (Sensor data : e.getSensorDataDirectory().getSensorDataList()) {
                    if (data.getSensorLocation().equalsIgnoreCase(sensorLocationId)) {
                        request.setSensorData(data);
                    }
                }
                request.setMessage(message);
                request.setSender(ua);
                request.setReceiver(r.getRoadMaintainer());
                request.setStatus("Sent");
                request.setRoad(r);
                JOptionPane.showMessageDialog(null, "Your request has been sent");
                problemjTextField.setText("");

                Organization org = null;
                for (Organization organization : e.getOrganizationDirectory().getOrganizationList()) {
                    if (organization instanceof RoadMaintenanceOrganization) {
                        org = organization;
                        break;
                    }
                }
                if (org != null) {
                    org.getWorkQueue().getWorkRequestList().add(request);
                    r.getRoadMaintainer().getWorkQueue().getWorkRequestList().add(request);
                    ua.getWorkQueue().getWorkRequestList().add(request);
                }
            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, " Please specify proper information", "Information", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_createRoadRequestjButtonActionPerformed

    public boolean validateProblem() {
        if (problemjTextField.getText().trim().equals("")) {
            problemjLabel.setText("Please enter the problem");
            return false;
        } else if (!problemjTextField.getText().matches("^[a-zA-Z ]*$")) {
            problemjLabel.setText("only characters");
            return false;
        } else {
            problemjLabel.setText("");
            return true;
        }
    }

    private void problemjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_problemjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_problemjTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JButton createRoadRequestjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel problemjLabel;
    private javax.swing.JTextField problemjTextField;
    private javax.swing.JTextField roadIdjTextField;
    private javax.swing.JTextField roadNamejTextField;
    // End of variables declaration//GEN-END:variables
}
