/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SensorSupplierRole;

import Business.Supplier.Products.Product;
import Business.Supplier.Supplier;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Leandra
 */
public class AddSensorJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Supplier s;

    /**
     * Creates new form AddSensorJPanel
     */
    public AddSensorJPanel(JPanel userProcessContainer, Supplier s) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.s = s;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        addjButton = new javax.swing.JButton();
        sensorIdjTextField = new javax.swing.JTextField();
        sensorPricejTextField = new javax.swing.JTextField();
        sensorQuantityjTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sensorNamejTextField = new javax.swing.JTextField();
        sensorNameJLabel = new javax.swing.JLabel();
        sensorIdNameJLabel = new javax.swing.JLabel();
        sensorPriceJLabel = new javax.swing.JLabel();
        sensorQuantityJLabel = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 36)); // NOI18N
        jLabel1.setText("Add Sensor");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel2.setText("Sensor ID:");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel3.setText("Sensor Price:");

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel4.setText("Sensor Quantity:");

        backjButton.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        backjButton.setText("Back");
        backjButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        addjButton.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        addjButton.setText("Add");
        addjButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        sensorIdjTextField.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        sensorIdjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sensorIdjTextFieldActionPerformed(evt);
            }
        });

        sensorPricejTextField.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N

        sensorQuantityjTextField.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N
        jLabel5.setText("Sensor Name:");

        sensorNamejTextField.setFont(new java.awt.Font("Segoe Print", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sensorNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sensorPricejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sensorQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(240, 240, 240)
                                .addComponent(sensorIdjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sensorIdNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sensorNameJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sensorPriceJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sensorQuantityJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(409, 409, 409)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sensorIdjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(sensorIdNameJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sensorNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(sensorNameJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(sensorPricejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(sensorPriceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sensorQuantityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sensorQuantityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(107, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:

        try {
            boolean idTrue = validateSensorId();
            boolean nameTrue = validateSensorName();
            boolean priceTrue = validateSensorPrice();
            boolean quantityTrue = validateSensorQuantity();

            if (idTrue && nameTrue && priceTrue && quantityTrue) {
                Product p = new Product();
                p.setProdId(Integer.parseInt(sensorIdjTextField.getText().trim()));
                p.setProdName(sensorNamejTextField.getText().trim());
                p.setPricePerUnit(Integer.parseInt(sensorPricejTextField.getText().trim()));
                p.setQuantity(Integer.parseInt(sensorQuantityjTextField.getText().trim()));
                s.getProductCatalog().addProduct(p);
                JOptionPane.showMessageDialog(null, "Sensor added successfully.", "Information", JOptionPane.INFORMATION_MESSAGE);
                sensorIdjTextField.setText("");
                sensorNamejTextField.setText("");
                sensorPricejTextField.setText("");
                sensorQuantityjTextField.setText("");

            }
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, " Please specify proper Sensor information", "Information", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_addjButtonActionPerformed

    public boolean validateSensorId() {
        if (sensorIdjTextField.getText().trim().equals("")) {
            sensorIdNameJLabel.setText("Please enter sensor ID");
            return false;
        } else if (!sensorIdjTextField.getText().matches("^[0-9]*$")) {
            sensorIdNameJLabel.setText("only numbers");
            return false;
        } else {
            sensorIdNameJLabel.setText("");
            return true;
        }
    }

    public boolean validateSensorName() {
        if (sensorNamejTextField.getText().trim().equals("")) {
            sensorNameJLabel.setText("Please enter sensor name");
            return false;
        } else if (!sensorNamejTextField.getText().matches("^[a-zA-Z]*$")) {
            sensorNameJLabel.setText("only characters");
            return false;
        } else {
            sensorNameJLabel.setText("");
            return true;
        }
    }

    public boolean validateSensorPrice() {
        if (sensorPricejTextField.getText().trim().equals("")) {
            sensorPriceJLabel.setText("Please enter sensor price");
            return false;
        } else if (!sensorPricejTextField.getText().matches("^[0-9]*$")) {
            sensorPriceJLabel.setText("only number");
            return false;
        } else {
            sensorPriceJLabel.setText("");
            return true;
        }
    }

    public boolean validateSensorQuantity() {
        if (sensorQuantityjTextField.getText().trim().equals("")) {
            sensorQuantityJLabel.setText("Please enter sensor quantity");
            return false;
        } else if (!sensorQuantityjTextField.getText().matches("^[0-9]*$")) {
            sensorQuantityJLabel.setText("only numbers");
            return false;
        } else {
            sensorQuantityJLabel.setText("");
            return true;
        }
    }

    private void sensorIdjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sensorIdjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sensorIdjTextFieldActionPerformed

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SensorSupplierCatalogJPanel sensorSupplierCatalogJPanel = (SensorSupplierCatalogJPanel) component;
        sensorSupplierCatalogJPanel.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backjButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel sensorIdNameJLabel;
    private javax.swing.JTextField sensorIdjTextField;
    private javax.swing.JLabel sensorNameJLabel;
    private javax.swing.JTextField sensorNamejTextField;
    private javax.swing.JLabel sensorPriceJLabel;
    private javax.swing.JTextField sensorPricejTextField;
    private javax.swing.JLabel sensorQuantityJLabel;
    private javax.swing.JTextField sensorQuantityjTextField;
    // End of variables declaration//GEN-END:variables
}
